"use client";

import { useEffect, useState } from "react";
import { Coins, Plus, Save, Trash2 } from "lucide-react";
import type { Reward } from "@/lib/rewards";

type RewardDraft = Reward;
const blankReward = (): RewardDraft => ({ id: `reward-${crypto.randomUUID()}`, title: "", description: "", cost: 500, kind: "perk", icon: "🎁", active: true, stock: 10, delivery: "" });

export function RewardsDashboard() {
  const [rewards, setRewards] = useState<RewardDraft[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  useEffect(() => { fetch("/api/rewards?admin=1", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((payload) => payload && setRewards(payload.rewards ?? [])).finally(() => setLoading(false)); }, []);
  const patch = (id: string, update: Partial<RewardDraft>) => setRewards((current) => current.map((reward) => reward.id === id ? { ...reward, ...update } : reward));
  async function save(reward: RewardDraft) { setSaving(reward.id); setNotice(""); try { const response = await fetch("/api/rewards", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(reward) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error ?? "تعذر حفظ المكافأة"); setRewards(payload.rewards ?? []); setNotice("تم حفظ متجر XP"); } catch (error) { setNotice(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setSaving(null); } }
  async function remove(id: string) { const response = await fetch(`/api/rewards?id=${encodeURIComponent(id)}`, { method: "DELETE" }); if (!response.ok) { const payload = await response.json().catch(() => ({})); setNotice(payload.error ?? "تعذر حذف المكافأة"); return; } setRewards((current) => current.filter((reward) => reward.id !== id)); }
  return <section className="rewards-admin admin-stack" dir="rtl"><div className="admin-block"><div className="admin-block__heading"><h4><Coins size={17} /> متجر XP</h4><button type="button" className="admin-refresh" onClick={() => setRewards((current) => [...current, blankReward()])}><Plus size={15} /> مكافأة جديدة</button></div><p className="admin-hint">السعر يخصم ذريًا من رصيد اللاعب، والمخزون لا يسمح بعمليات استبدال بعد النفاد.</p>{notice && <p className="admin-hint">{notice}</p>}</div>{loading ? <p className="admin-empty">جارٍ تحميل الجوائز...</p> : rewards.map((reward) => <article className="reward-admin-card" key={reward.id}><div className="reward-admin-card__top"><input value={reward.icon} maxLength={4} onChange={(event) => patch(reward.id, { icon: event.target.value })} aria-label="أيقونة المكافأة" /><input value={reward.title} onChange={(event) => patch(reward.id, { title: event.target.value })} placeholder="اسم المكافأة" /><label><input type="checkbox" checked={reward.active} onChange={(event) => patch(reward.id, { active: event.target.checked })} /> مفعلة</label></div><div className="admin-grid"><label className="admin-field">المعرّف<input className="admin-input" value={reward.id} onChange={(event) => patch(reward.id, { id: event.target.value })} /></label><label className="admin-field">السعر<input className="admin-input" type="number" min={1} value={reward.cost} onChange={(event) => patch(reward.id, { cost: Number(event.target.value) || 1 })} /></label><label className="admin-field">المخزون<input className="admin-input" type="number" min={0} value={reward.stock} onChange={(event) => patch(reward.id, { stock: Number(event.target.value) || 0 })} /></label><label className="admin-field">النوع<select className="admin-select" value={reward.kind} onChange={(event) => patch(reward.id, { kind: event.target.value as Reward["kind"] })}><option value="code">كود رقمي</option><option value="ticket">تذكرة</option><option value="perk">ميزة</option></select></label></div><textarea className="admin-textarea" value={reward.description} onChange={(event) => patch(reward.id, { description: event.target.value })} placeholder="وصف المكافأة" /><input className="admin-input" value={reward.delivery ?? ""} onChange={(event) => patch(reward.id, { delivery: event.target.value })} placeholder="نص التسليم أو الكود" /><div className="admin-actions"><button type="button" className="gaming-button" onClick={() => save(reward)} disabled={saving === reward.id}><Save size={15} /> {saving === reward.id ? "جارٍ الحفظ..." : "حفظ"}</button><button type="button" className="admin-refresh" onClick={() => remove(reward.id)}><Trash2 size={15} /> حذف</button></div></article>)}</section>;
}
